# Generated by Django 5.2.4 on 2025-08-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_oderupdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderUpdates',
            new_name='OrderUpdate',
        ),
    ]
